android.enableJetifier=false
android.nonFinalResIds=false
android.nonTransitiveRClass=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048M --add-opens jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
systemProp.file.encoding=utf-8
# always set testOnly to false in gradle.properties to get debug builds installed
android.injected.testOnly=false

# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
